# lang.py

LANG = {
    "ja": {
        "title":                   "💰 The Life-Value Optimizer",
        "caption":                 "限られた予算で、人生の質を最大化する",
        "step1":                   "Step 1: あなたについて",
        "age":                     "年齢",
        "gender":                  "性別",
        "gender_options":          ["回答しない", "男性", "女性", "その他"],
        "family":                  "家族構成",
        "family_options":          ["一人暮らし", "夫婦", "夫婦＋子供1人", "夫婦＋子供2人", "夫婦＋子供3人", "夫婦＋子供4人", "その他"],
        "monthly_income":          "月収（税引後）（$）",
        "fixed_costs_title":       "固定費（毎月必ず発生するもの）",
        "rent":                    "家賃 / 住宅ローン（$）",
        "utilities":               "電気・ガス・水道（$）",
        "internet":                "インターネット・通信費（$）",
        "groceries":               "食費（基本）（$）",
        "health_insurance_fixed":  "医療保険（$）",
        "other_fixed":             "その他固定費（$）",
        "disposable_income":       "可処分所得（自動計算）",
        "disposable_income_help":  "月収 − 固定費合計。これが最適化の月次予算上限になります",
        "total_budget":            "初期費用の上限（$）",
        "total_budget_help":       "車・家電など一回限りの購入費用の合計上限",
        "step2":                   "Step 2: 目標設定",
        "savings_goal":            "貯蓄目標額（$）",
        "savings_period":          "達成期間",
        "monthly_savings_cap":     "月次目標貯蓄額：${}/月",
        "priority":                "目標の優先度",
        "goal_type":               "目標タイプ",
        "goal_options":            ["健康的に過ごす", "お金を貯める", "快適に過ごす", "カスタム"],
        "w_time":                  "⏱ 時間節約",
        "w_health":                "💪 健康",
        "w_satisfaction":          "😊 満足度",
        "w_savings":               "💰 貯蓄",
        "step_lifestyle":          "Step 2.5: ライフスタイル設定",
        "diet_label":              "食事嗜好",
        "diet_options":            ["健康志向", "標準", "ファストフード", "外食多め"],
        "exercise_label":          "運動頻度",
        "exercise_options":        ["週5以上", "週2〜4", "週1以下"],
        "smoking_label":           "タバコ",
        "smoking_options":         ["なし", "ライト（1日1〜5本）", "ミディアム（1日6〜15本）", "ヘビー（1日16本以上）"],
        "alcohol_label":           "お酒",
        "alcohol_options":         ["ほぼ飲まない", "週1〜2杯", "週3〜5杯", "毎日"],
        "income_title":            "将来の収入増見込み",
        "income_increase":         "月次収入増額（$）",
        "income_years":            "実現見込み（年後）",
        "income_reason":           "理由",
        "lifestyle_diet_note":     "食事嗜好による月次食費補正",
        "lifestyle_health_note":   "運動・嗜好による健康スコア補正",
        "step3":                   "Step 3: アイテム選択",
        "step3_caption":           "優先度が入力されたアイテムが最適化の候補になります（0=対象外）。費用は実情に合わせて編集可能です。",
        "col_name":                "アイテム名",
        "col_initial":             "初期費用($)",
        "col_monthly":             "月次費用($)",
        "col_time":                "⏱",
        "col_health":              "💪",
        "col_satisfaction":        "😊",
        "col_priority":            "優先度",
        "col_mandatory":           "必須",
        "col_note":                "備考",
        "priority_help":           "0=対象外、1以上=候補（数字が小さいほど優先）。同じ数字は同じ優先度",
        "candidates_count":        "{}件が候補",
        "ai_item_placeholder":     "アイテム名を入力（例：ジム、車）",
        "ai_complete_button":      "🤖 AI追加",
        "ai_summary_title":        "🤖 AIサマリー",
        "ai_error_complete":       "AI補完に失敗しました。手動で入力してください。",
        "ai_error_summary":        "サマリーの生成に失敗しました。",
        "risk_toggle":             "現実的なリスクコストを考慮する",
        "risk_title":              "⚠️ リスクコスト予測",
        "risk_caption":            "将来かかる可能性のある費用（保険でカバーされない自己負担分等）。編集可能です。",
        "risk_col_category":       "カテゴリ",
        "risk_col_cost":           "月次コスト($)",
        "risk_effective":          "リスクコスト考慮後の実質月次予算",
        "risk_categories": {
            "medical":    "医療費自己負担（コプレイ等）",
            "housing":    "住居修繕費",
            "car_repair": "車の修理費",
            "education":  "教育費",
            "emergency":  "緊急予備費",
        },
        "run_button":              "🚀 最適化を実行",
        "mandatory_summary_title": "必須・候補アイテムの費用サマリー",
        "must_initial":            "必須：初期費用合計",
        "must_monthly":            "必須：月次費用合計",
        "cand_initial":            "候補：初期費用合計",
        "cand_monthly":            "候補：月次費用合計",
        "validation_initial_over": "❌ 必須アイテムの初期費用合計（${:,}）が上限（${:,}）を超えています",
        "validation_monthly_over": "❌ 必須アイテムの月次費用合計（${:,}）が実質予算（${:,}）を超えています",
        "validation_no_transport": "⚠️ 移動手段カテゴリに候補が1つもありません。優先度を設定してください。",
        "result_ok":               "✅ 最適な組み合わせが見つかりました",
        "result_ng":               "❌ 条件を満たす組み合わせが見つかりませんでした。予算や必須アイテムを見直してください。",
        "total_initial":           "初期費用合計",
        "total_monthly":           "月次費用合計",
        "actual_savings":          "実際の月次貯蓄",
        "savings_rate":            "貯蓄目標達成率",
        "shortfall_warn":          "⚠️ 目標貯蓄額まであと **${}/月** 不足しています。",
        "selected_items":          "選ばれたアイテム",
        "rec_title":               "💡 推奨アクション",
        "rec_can_add":             "現在の予算で **{}** を追加できます（初期費用${:,} / 月次費用${:,}）",
        "rec_budget_up":           "月次予算をあと **${}** 増やすと **{}** を追加できます",
        "sensitivity_title":       "📊 感度分析",
        "tab_monthly":             "月次予算",
        "tab_initial":             "初期費用上限",
        "chart_value":             "合計バリュー",
        "chart_monthly_x":         "月次予算 ($)",
        "chart_initial_x":         "初期費用上限 ($)",
        "chart_line_title_m":      "月次予算 vs 合計バリュー",
        "chart_heat_title_m":      "月次予算ごとのアイテム選択",
        "chart_line_title_i":      "初期費用上限 vs 合計バリュー",
        "chart_heat_title_i":      "初期費用上限ごとのアイテム選択",
        "rec_title":       "💡 あなたの満足度を上げる次の一手",
        "rec_next_item":   "優先度{}: **{}**  初期費用${:,} / 月次費用${:,}  → あと**${}**/月あれば追加できます",
        "rec_within_budget":"予算内で追加可能",
    },
    "en": {
        "title":                   "💰 The Life-Value Optimizer",
        "caption":                 "Maximize your life quality within a limited budget",
        "step1":                   "Step 1: About You",
        "age":                     "Age",
        "gender":                  "Gender",
        "gender_options":          ["Prefer not to say", "Male", "Female", "Other"],
        "family":                  "Household",
        "family_options":          ["Single", "Couple", "Couple + 1 Kid", "Couple + 2 Kids", "Couple + 3 Kids", "Couple + 4 Kids", "Other"],
        "monthly_income":          "Monthly Income (after tax) ($)",
        "fixed_costs_title":       "Fixed Costs (monthly necessities)",
        "rent":                    "Rent / Mortgage ($)",
        "utilities":               "Utilities (Electric/Gas/Water) ($)",
        "internet":                "Internet & Phone ($)",
        "groceries":               "Groceries (basic) ($)",
        "health_insurance_fixed":  "Health Insurance ($)",
        "other_fixed":             "Other Fixed Costs ($)",
        "disposable_income":       "Disposable Income (auto-calculated)",
        "disposable_income_help":  "Income − Fixed costs. This becomes your monthly budget for optimization.",
        "total_budget":            "Initial Cost Limit ($)",
        "total_budget_help":       "Total limit for one-time purchases (car, appliances, etc.)",
        "step2":                   "Step 2: Goal Setting",
        "savings_goal":            "Savings Goal ($)",
        "savings_period":          "Target Period",
        "monthly_savings_cap":     "Monthly savings target: ${}/month",
        "priority":                "Priority Weights",
        "goal_type":               "Goal Type",
        "goal_options":            ["Stay Healthy", "Save Money", "Live Comfortably", "Custom"],
        "w_time":                  "⏱ Time Saving",
        "w_health":                "💪 Health",
        "w_satisfaction":          "😊 Satisfaction",
        "w_savings":               "💰 Savings",
        "step_lifestyle":          "Step 2.5: Lifestyle Settings",
        "diet_label":              "Dietary Preference",
        "diet_options":            ["Health-conscious", "Standard", "Fast Food", "Eat Out Often"],
        "exercise_label":          "Exercise Frequency",
        "exercise_options":        ["5+ days/week", "2-4 days/week", "1 or less/week"],
        "smoking_label":           "Smoking",
        "smoking_options":         ["None", "Light (1-5/day)", "Medium (6-15/day)", "Heavy (16+/day)"],
        "alcohol_label":           "Alcohol",
        "alcohol_options":         ["Rarely", "1-2 times/week", "3-5 times/week", "Daily"],
        "income_title":            "Future Income Projection",
        "income_increase":         "Monthly Income Increase ($)",
        "income_years":            "Expected in (years)",
        "income_reason":           "Reason",
        "lifestyle_diet_note":     "Monthly food cost adjustment",
        "lifestyle_health_note":   "Health score adjustment",
        "step3":                   "Step 3: Item Selection",
        "step3_caption":           "Items with a priority number become optimization candidates (0 = excluded). You can edit costs to match your situation.",
        "col_name":                "Item",
        "col_initial":             "Initial($)",
        "col_monthly":             "Monthly($)",
        "col_time":                "⏱",
        "col_health":              "💪",
        "col_satisfaction":        "😊",
        "col_priority":            "Priority",
        "col_mandatory":           "Must",
        "col_note":                "Note",
        "priority_help":           "0=excluded, 1+=candidate (lower=higher priority). Same number = same priority.",
        "candidates_count":        "{} candidates",
        "ai_item_placeholder":     "Enter item name (e.g. Gym, Car)",
        "ai_complete_button":      "🤖 AI Add",
        "ai_summary_title":        "🤖 AI Summary",
        "ai_error_complete":       "AI completion failed. Please fill in manually.",
        "ai_error_summary":        "Failed to generate summary.",
        "risk_toggle":             "Consider realistic risk costs",
        "risk_title":              "⚠️ Risk Cost Estimate",
        "risk_caption":            "Estimated out-of-pocket costs not covered by insurance. You can edit these values.",
        "risk_col_category":       "Category",
        "risk_col_cost":           "Monthly Cost($)",
        "risk_effective":          "Effective monthly budget after risk costs",
        "risk_categories": {
            "medical":    "Medical Out-of-Pocket (copay etc.)",
            "housing":    "Housing Repair",
            "car_repair": "Car Repair",
            "education":  "Education",
            "emergency":  "Emergency Fund",
        },
        "run_button":              "🚀 Optimize",
        "mandatory_summary_title": "Mandatory & Candidate Cost Summary",
        "must_initial":            "Must: Total Initial",
        "must_monthly":            "Must: Total Monthly",
        "cand_initial":            "Candidates: Total Initial",
        "cand_monthly":            "Candidates: Total Monthly",
        "validation_initial_over": "❌ Mandatory items total initial cost (${:,}) exceeds limit (${:,})",
        "validation_monthly_over": "❌ Mandatory items total monthly cost (${:,}) exceeds effective budget (${:,})",
        "validation_no_transport": "⚠️ No transport candidates selected. Please set a priority for at least one.",
        "result_ok":               "✅ Optimal combination found",
        "result_ng":               "❌ No valid combination found. Please review your budget or mandatory items.",
        "total_initial":           "Total Initial Cost",
        "total_monthly":           "Total Monthly Cost",
        "actual_savings":          "Actual Monthly Savings",
        "savings_rate":            "Savings Goal Rate",
        "shortfall_warn":          "⚠️ **${}/month** short of your savings goal.",
        "selected_items":          "Selected Items",
        "rec_title":               "💡 Recommendations",
        "rec_can_add":             "You can add **{}** now (Initial: ${:,} / Monthly: ${:,})",
        "rec_budget_up":           "Increase monthly budget by **${}** to add **{}**",
        "sensitivity_title":       "📊 Sensitivity Analysis",
        "tab_monthly":             "Monthly Budget",
        "tab_initial":             "Initial Cost Limit",
        "chart_value":             "Total Value",
        "chart_monthly_x":         "Monthly Budget ($)",
        "chart_initial_x":         "Initial Cost Limit ($)",
        "chart_line_title_m":      "Monthly Budget vs Total Value",
        "chart_heat_title_m":      "Item Selection by Monthly Budget",
        "chart_line_title_i":      "Initial Cost Limit vs Total Value",
        "chart_heat_title_i":      "Item Selection by Initial Cost Limit",
        "rec_title":       "💡 Next steps to boost your satisfaction",
        "rec_next_item":   "Priority {}: **{}**  Initial${:,} / Monthly${:,}  → **${}**/month more needed",
        "rec_within_budget":"Can be added within budget",
    }
}

PRESETS = {
    "ja": {
        "健康的に過ごす": {"time": 2, "health": 9, "satisfaction": 3, "savings": 1},
        "お金を貯める":   {"time": 1, "health": 2, "satisfaction": 1, "savings": 9},
        "快適に過ごす":   {"time": 4, "health": 5, "satisfaction": 8, "savings": 2},
        "カスタム":       {"time": 5, "health": 5, "satisfaction": 5, "savings": 5},
    },
    "en": {
        "Stay Healthy":     {"time": 2, "health": 9, "satisfaction": 3, "savings": 1},
        "Save Money":       {"time": 1, "health": 2, "satisfaction": 1, "savings": 9},
        "Live Comfortably": {"time": 4, "health": 5, "satisfaction": 8, "savings": 2},
        "Custom":           {"time": 5, "health": 5, "satisfaction": 5, "savings": 5},
    }
}