# lang.py
# 全UIテキストの日英辞書

LANG = {
    "ja": {
        "title":                "💰 The Life-Value Optimizer",
        "caption":              "限られた予算で、人生の質を最大化する",
        "step1":                "Step 1: あなたについて",
        "age":                  "年齢",
        "gender":               "性別",
        "gender_options":       ["回答しない", "男性", "女性", "その他"],
        "family":               "家族構成",
        "family_options":       ["一人暮らし", "夫婦", "夫婦＋子供", "その他"],
        "horizon":              "タイムホライズン",
        "monthly_budget":       "月次予算（$）",
        "total_budget":         "初期費用の上限（$）",
        "total_budget_help":    "車・自転車など一回限りの購入費用の合計上限",
        "step2":                "Step 2: 目標設定",
        "savings_goal":         "貯蓄目標額（$）",
        "savings_period":       "達成期間",
        "monthly_savings_cap":  "月次目標貯蓄額：${}/月",
        "priority":             "目標の優先度",
        "goal_type":            "目標タイプ",
        "goal_options":         ["健康的に過ごす", "お金を貯める", "快適に過ごす", "カスタム"],
        "w_time":               "⏱ 時間節約",
        "w_health":             "💪 健康",
        "w_satisfaction":       "😊 満足度",
        "w_savings":            "💰 貯蓄",
        "step3":                "Step 3: アイテムリスト",
        "col_name":             "名前",
        "col_initial":          "初期費用($)",
        "col_monthly":          "月次費用($)",
        "col_time":             "時間節約",
        "col_health":           "健康",
        "col_satisfaction":     "満足度",
        "run_button":           "🚀 最適化を実行",
        "result_ok":            "✅ 最適な組み合わせが見つかりました",
        "result_ng":            "❌ 条件を満たす組み合わせが見つかりませんでした。予算を見直してください。",
        "total_initial":        "初期費用合計",
        "total_monthly":        "月次費用合計",
        "actual_savings":       "実際の月次貯蓄",
        "savings_rate":         "貯蓄目標達成率",
        "shortfall_warn":       "⚠️ 目標貯蓄額まであと **${}/月** 不足しています。貯蓄への重みを上げるか、アイテムを見直してください。",
        "selected_items":       "選ばれたアイテム",
        "sensitivity_title":    "📊 感度分析",
        "tab_monthly":          "月次予算",
        "tab_initial":          "初期費用上限",
        "chart_value":          "合計バリュー",
        "chart_monthly_x":      "月次予算 ($)",
        "chart_initial_x":      "初期費用上限 ($)",
        "chart_heatmap_y":      "アイテム",
        "chart_heatmap_sel":    "選択",
        "chart_line_title_m":   "月次予算 vs 合計バリュー",
        "chart_heat_title_m":   "月次予算ごとのアイテム選択",
        "chart_line_title_i":   "初期費用上限 vs 合計バリュー",
        "chart_heat_title_i":   "初期費用上限ごとのアイテム選択",
        "current_line":         "現在の設定",
        "ai_item_placeholder":  "アイテム名を入力（例：ジム、車）",
        "ai_complete_button":   "🤖 AIで補完して追加",
        "ai_summary_title":     "🤖 AIサマリー",
        "ai_error_complete":    "AI補完に失敗しました。手動で入力してください。",
        "ai_error_summary":     "サマリーの生成に失敗しました。",
        "rec_title":            "💡 推奨アクション",
        "rec_can_add":          "現在の予算で **{}** を追加できます（初期費用${:,} / 月次費用${:,}）",
        "rec_budget_up":        "月次予算をあと **${}** 増やすと **{}** を追加できます",
    },
    "en": {
        "title":                "💰 The Life-Value Optimizer",
        "caption":              "Maximize your life quality within a limited budget",
        "step1":                "Step 1: About You",
        "age":                  "Age",
        "gender":               "Gender",
        "gender_options":       ["Prefer not to say", "Male", "Female", "Other"],
        "family":               "Household",
        "family_options":       ["Single", "Couple", "Couple + Kids", "Other"],
        "horizon":              "Time Horizon",
        "monthly_budget":       "Monthly Budget ($)",
        "total_budget":         "Initial Cost Limit ($)",
        "total_budget_help":    "Total limit for one-time purchases (car, bike, etc.)",
        "step2":                "Step 2: Goal Setting",
        "savings_goal":         "Savings Goal ($)",
        "savings_period":       "Target Period",
        "monthly_savings_cap":  "Monthly savings target: ${}/month",
        "priority":             "Priority Weights",
        "goal_type":            "Goal Type",
        "goal_options":         ["Stay Healthy", "Save Money", "Live Comfortably", "Custom"],
        "w_time":               "⏱ Time Saving",
        "w_health":             "💪 Health",
        "w_satisfaction":       "😊 Satisfaction",
        "w_savings":            "💰 Savings",
        "step3":                "Step 3: Item List",
        "col_name":             "Name",
        "col_initial":          "Initial Cost($)",
        "col_monthly":          "Monthly Cost($)",
        "col_time":             "Time Saving",
        "col_health":           "Health",
        "col_satisfaction":     "Satisfaction",
        "run_button":           "🚀 Optimize",
        "result_ok":            "✅ Optimal combination found",
        "result_ng":            "❌ No valid combination found. Please review your budget.",
        "total_initial":        "Total Initial Cost",
        "total_monthly":        "Total Monthly Cost",
        "actual_savings":       "Actual Monthly Savings",
        "savings_rate":         "Savings Goal Rate",
        "shortfall_warn":       "⚠️ **${}/month** short of your savings goal. Try increasing savings weight or reviewing items.",
        "selected_items":       "Selected Items",
        "sensitivity_title":    "📊 Sensitivity Analysis",
        "tab_monthly":          "Monthly Budget",
        "tab_initial":          "Initial Cost Limit",
        "chart_value":          "Total Value",
        "chart_monthly_x":      "Monthly Budget ($)",
        "chart_initial_x":      "Initial Cost Limit ($)",
        "chart_heatmap_y":      "Item",
        "chart_heatmap_sel":    "Selected",
        "chart_line_title_m":   "Monthly Budget vs Total Value",
        "chart_heat_title_m":   "Item Selection by Monthly Budget",
        "chart_line_title_i":   "Initial Cost Limit vs Total Value",
        "chart_heat_title_i":   "Item Selection by Initial Cost Limit",
        "current_line":         "Current Setting",
        "ai_item_placeholder":  "Enter item name (e.g. Gym, Car)",
        "ai_complete_button":   "🤖 AI Auto-fill & Add",
        "ai_summary_title":     "🤖 AI Summary",
        "ai_error_complete":    "AI completion failed. Please fill in manually.",
        "ai_error_summary":     "Failed to generate summary.",
        "rec_title":            "💡 Recommendations",
        "rec_can_add":          "You can add **{}** now (Initial: ${:,} / Monthly: ${:,})",
        "rec_budget_up":        "Increase monthly budget by **${}** to add **{}**",
    }
}

PRESETS = {
    "ja": {
        "健康的に過ごす":  {"time": 2, "health": 9, "satisfaction": 3, "savings": 1},
        "お金を貯める":    {"time": 1, "health": 2, "satisfaction": 1, "savings": 9},
        "快適に過ごす":    {"time": 4, "health": 5, "satisfaction": 8, "savings": 2},
        "カスタム":        {"time": 5, "health": 5, "satisfaction": 5, "savings": 5},
    },
    "en": {
        "Stay Healthy":       {"time": 2, "health": 9, "satisfaction": 3, "savings": 1},
        "Save Money":         {"time": 1, "health": 2, "satisfaction": 1, "savings": 9},
        "Live Comfortably":   {"time": 4, "health": 5, "satisfaction": 8, "savings": 2},
        "Custom":             {"time": 5, "health": 5, "satisfaction": 5, "savings": 5},
    }
}